
GET http://localhost:3000/week-12/part-2/api/dogs

###

POST http://localhost:3000/week-12/part-2/api/dogs HTTP/1.1
content-type: application/json

{
    "name": "Sparky",
    "age": 4
}

###

GET http://localhost:3000/week-12/part-2/api/dogs/3

###

PUT http://localhost:3000/week-12/part-2/api/dogs/1 HTTP/1.1
content-type: application/json

{
    "name": "Bob",
    "age": 5
}

###
PATCH http://localhost:3000/week-12/part-2/api/dogs/1 HTTP/1.1
content-type: application/json

{
    "age": 5
}

###

DELETE http://localhost:3000/week-12/part-2/api/dogs/1